# Generated by Django 3.2.11 on 2022-02-06 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일 주소 / ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now, verbose_name='생년월일')),
                ('is_active', models.BooleanField(default=False, verbose_name='활성화')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='관리자')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='생성일자')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(verbose_name='작성일자')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20, unique=True, verbose_name='직급')),
            ],
            options={
                'verbose_name': '직급',
                'verbose_name_plural': '직급',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '권한',
                'verbose_name_plural': '권한',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(verbose_name='작성일자')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
            ],
        ),
        migrations.CreateModel(
            name='Wrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=30)),
                ('content_name', models.CharField(max_length=30)),
                ('create_date', models.DateTimeField(verbose_name='작성일자')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
