# Generated by Django 3.2.11 on 2022-02-06 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('task', '0001_initial'),
        ('bulletinboard', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrapper',
            name='estimator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.estimator'),
        ),
        migrations.AddField(
            model_name='wrapper',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bulletinboard.post'),
        ),
        migrations.AddField(
            model_name='reply',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='wrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.wrapper'),
        ),
        migrations.AddField(
            model_name='level',
            name='permission',
            field=models.ManyToManyField(related_name='perms', to='common.Permission', verbose_name='권한'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.reply'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.level', verbose_name='직급'),
        ),
    ]
