# Generated by Django 3.2.11 on 2022-02-23 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_estimatortype_name'),
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrapper',
            name='contiainer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.estimatorcontainer'),
        ),
    ]
