# Generated by Django 3.2.11 on 2022-02-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='config',
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default=1, max_length=30, verbose_name='종류'),
            preserve_default=False,
        ),
    ]
