# Generated by Django 3.2.11 on 2022-02-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20220206_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='status',
            field=models.CharField(blank=True, choices=[('1', '신청'), ('2', '승인'), ('3', '반려')], max_length=20, null=True),
        ),
    ]
