# Generated by Django 3.2.11 on 2022-02-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_vacation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskconfig',
            options={'verbose_name': '업무 종류', 'verbose_name_plural': '업무 종류'},
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
