# Generated by Django 3.2.11 on 2022-02-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20220209_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='status',
            field=models.CharField(blank=True, choices=[('1', '신청'), ('2', '승인'), ('3', '반려')], max_length=20, null=True, verbose_name='상태'),
        ),
    ]
