# Generated by Django 3.2.11 on 2022-03-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletinboard', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notice',
            field=models.BooleanField(blank=True, null=True, verbose_name='상단고정게시물'),
        ),
    ]
