# Generated by Django 3.2.11 on 2022-02-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimator',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='견적서 명'),
        ),
        migrations.AlterField(
            model_name='estimator',
            name='type',
            field=models.CharField(max_length=30, verbose_name='품목'),
        ),
    ]
