# Generated by Django 3.2.11 on 2022-02-19 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_auto_20220209_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatorContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='작성일자')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정일자')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='견적서 뭉치 명')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '견적서 뭉치치',
                'verbose_name_plural': '견적서 뭉치',
            },
        ),
        migrations.AddField(
            model_name='estimator',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.estimatorcontainer'),
        ),
    ]
