# Generated by Django 3.2.11 on 2022-02-19 11:35

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20220219_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatortype',
            name='kwargs',
            field=picklefield.fields.PickledObjectField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
