# Generated by Django 3.2.11 on 2022-02-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_estimatortype_kwargs'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatortype',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
