# Generated by Django 3.2.11 on 2022-02-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_estimatortype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimator',
            name='author',
        ),
        migrations.RemoveField(
            model_name='estimator',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='estimator',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='estimator',
            name='name',
        ),
    ]
