# Generated by Django 3.2.11 on 2022-02-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20220223_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatorcontainer',
            name='customer',
            field=models.CharField(max_length=200, null=True, verbose_name='고객사'),
        ),
    ]
